/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.wibidata.wikimedia.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum IdTypes { 
  UNAME, IP, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IdTypes\",\"namespace\":\"com.wibidata.wikimedia.avro\",\"symbols\":[\"UNAME\",\"IP\",\"UNKNOWN\"],\"aliases\":[\"com.odiago.wikimedia.avro.IdTypes\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
