/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.wibidata.wikimedia.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum RevertTypes { 
  REVERTING, REVERTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RevertTypes\",\"namespace\":\"com.wibidata.wikimedia.avro\",\"symbols\":[\"REVERTING\",\"REVERTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
