/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.wibidata.wikimedia.avro;  
@SuppressWarnings("all")
/** Info about the templates contained in the whole page. */
@org.apache.avro.specific.AvroGenerated
public class TemplateRecordArray extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TemplateRecordArray\",\"namespace\":\"com.wibidata.wikimedia.avro\",\"doc\":\"Info about the templates contained in the whole page.\",\"fields\":[{\"name\":\"recordArray\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"TemplateRecord\",\"doc\":\"Info about the templates contained in the whole page.\",\"fields\":[{\"name\":\"templateText\",\"type\":\"string\",\"doc\":\"The text contained inside of an outermost pair of curly braces, inclusive.\"},{\"name\":\"startOffset\",\"type\":\"long\",\"doc\":\"The offset into the revision text where the template begins.\"},{\"name\":\"endOffset\",\"type\":\"long\",\"doc\":\"The offset into the revision text of the last template character.\"}],\"aliases\":[\"com.odiago.wikimedia.avro.TemplateRecord\"]}},\"doc\":\"An array of all records for every template within the wiki page.\"}],\"aliases\":[\"com.odiago.wikimedia.avro.TemplateRecordArray\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** An array of all records for every template within the wiki page. */
  @Deprecated public java.util.List<com.wibidata.wikimedia.avro.TemplateRecord> recordArray;

  /**
   * Default constructor.
   */
  public TemplateRecordArray() {}

  /**
   * All-args constructor.
   */
  public TemplateRecordArray(java.util.List<com.wibidata.wikimedia.avro.TemplateRecord> recordArray) {
    this.recordArray = recordArray;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return recordArray;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: recordArray = (java.util.List<com.wibidata.wikimedia.avro.TemplateRecord>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'recordArray' field.
   * An array of all records for every template within the wiki page.   */
  public java.util.List<com.wibidata.wikimedia.avro.TemplateRecord> getRecordArray() {
    return recordArray;
  }

  /**
   * Sets the value of the 'recordArray' field.
   * An array of all records for every template within the wiki page.   * @param value the value to set.
   */
  public void setRecordArray(java.util.List<com.wibidata.wikimedia.avro.TemplateRecord> value) {
    this.recordArray = value;
  }

  /** Creates a new TemplateRecordArray RecordBuilder */
  public static com.wibidata.wikimedia.avro.TemplateRecordArray.Builder newBuilder() {
    return new com.wibidata.wikimedia.avro.TemplateRecordArray.Builder();
  }
  
  /** Creates a new TemplateRecordArray RecordBuilder by copying an existing Builder */
  public static com.wibidata.wikimedia.avro.TemplateRecordArray.Builder newBuilder(com.wibidata.wikimedia.avro.TemplateRecordArray.Builder other) {
    return new com.wibidata.wikimedia.avro.TemplateRecordArray.Builder(other);
  }
  
  /** Creates a new TemplateRecordArray RecordBuilder by copying an existing TemplateRecordArray instance */
  public static com.wibidata.wikimedia.avro.TemplateRecordArray.Builder newBuilder(com.wibidata.wikimedia.avro.TemplateRecordArray other) {
    return new com.wibidata.wikimedia.avro.TemplateRecordArray.Builder(other);
  }
  
  /**
   * RecordBuilder for TemplateRecordArray instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TemplateRecordArray>
    implements org.apache.avro.data.RecordBuilder<TemplateRecordArray> {

    private java.util.List<com.wibidata.wikimedia.avro.TemplateRecord> recordArray;

    /** Creates a new Builder */
    private Builder() {
      super(com.wibidata.wikimedia.avro.TemplateRecordArray.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.wibidata.wikimedia.avro.TemplateRecordArray.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing TemplateRecordArray instance */
    private Builder(com.wibidata.wikimedia.avro.TemplateRecordArray other) {
            super(com.wibidata.wikimedia.avro.TemplateRecordArray.SCHEMA$);
      if (isValidValue(fields()[0], other.recordArray)) {
        this.recordArray = data().deepCopy(fields()[0].schema(), other.recordArray);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'recordArray' field */
    public java.util.List<com.wibidata.wikimedia.avro.TemplateRecord> getRecordArray() {
      return recordArray;
    }
    
    /** Sets the value of the 'recordArray' field */
    public com.wibidata.wikimedia.avro.TemplateRecordArray.Builder setRecordArray(java.util.List<com.wibidata.wikimedia.avro.TemplateRecord> value) {
      validate(fields()[0], value);
      this.recordArray = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'recordArray' field has been set */
    public boolean hasRecordArray() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'recordArray' field */
    public com.wibidata.wikimedia.avro.TemplateRecordArray.Builder clearRecordArray() {
      recordArray = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public TemplateRecordArray build() {
      try {
        TemplateRecordArray record = new TemplateRecordArray();
        record.recordArray = fieldSetFlags()[0] ? this.recordArray : (java.util.List<com.wibidata.wikimedia.avro.TemplateRecord>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
