/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kiji.express.wikimedia;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Categories {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Categories\",\"namespace\":\"org.kiji.express.wikimedia\",\"types\":[{\"type\":\"record\",\"name\":\"CategoriesRecord\",\"doc\":\"* A custom Avro record to hold complex types for the 'categories' column of the Wikimedia\\n    * 'page' table. Specifically, categories are an array of strings.\",\"fields\":[{\"name\":\"categories\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Categories {
    public static final org.apache.avro.Protocol PROTOCOL = org.kiji.express.wikimedia.Categories.PROTOCOL;
  }
}