/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kiji.express.wikimedia;  
@SuppressWarnings("all")
/** * A custom Avro record to hold complex types for the 'categories' column of the Wikimedia
    * 'page' table. Specifically, categories are an array of strings. */
@org.apache.avro.specific.AvroGenerated
public class CategoriesRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CategoriesRecord\",\"namespace\":\"org.kiji.express.wikimedia\",\"doc\":\"* A custom Avro record to hold complex types for the 'categories' column of the Wikimedia\\n    * 'page' table. Specifically, categories are an array of strings.\",\"fields\":[{\"name\":\"categories\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.CharSequence> categories;

  /**
   * Default constructor.
   */
  public CategoriesRecord() {}

  /**
   * All-args constructor.
   */
  public CategoriesRecord(java.util.List<java.lang.CharSequence> categories) {
    this.categories = categories;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return categories;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: categories = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'categories' field.
   */
  public java.util.List<java.lang.CharSequence> getCategories() {
    return categories;
  }

  /**
   * Sets the value of the 'categories' field.
   * @param value the value to set.
   */
  public void setCategories(java.util.List<java.lang.CharSequence> value) {
    this.categories = value;
  }

  /** Creates a new CategoriesRecord RecordBuilder */
  public static org.kiji.express.wikimedia.CategoriesRecord.Builder newBuilder() {
    return new org.kiji.express.wikimedia.CategoriesRecord.Builder();
  }
  
  /** Creates a new CategoriesRecord RecordBuilder by copying an existing Builder */
  public static org.kiji.express.wikimedia.CategoriesRecord.Builder newBuilder(org.kiji.express.wikimedia.CategoriesRecord.Builder other) {
    return new org.kiji.express.wikimedia.CategoriesRecord.Builder(other);
  }
  
  /** Creates a new CategoriesRecord RecordBuilder by copying an existing CategoriesRecord instance */
  public static org.kiji.express.wikimedia.CategoriesRecord.Builder newBuilder(org.kiji.express.wikimedia.CategoriesRecord other) {
    return new org.kiji.express.wikimedia.CategoriesRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for CategoriesRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CategoriesRecord>
    implements org.apache.avro.data.RecordBuilder<CategoriesRecord> {

    private java.util.List<java.lang.CharSequence> categories;

    /** Creates a new Builder */
    private Builder() {
      super(org.kiji.express.wikimedia.CategoriesRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.kiji.express.wikimedia.CategoriesRecord.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing CategoriesRecord instance */
    private Builder(org.kiji.express.wikimedia.CategoriesRecord other) {
            super(org.kiji.express.wikimedia.CategoriesRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.categories)) {
        this.categories = data().deepCopy(fields()[0].schema(), other.categories);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'categories' field */
    public java.util.List<java.lang.CharSequence> getCategories() {
      return categories;
    }
    
    /** Sets the value of the 'categories' field */
    public org.kiji.express.wikimedia.CategoriesRecord.Builder setCategories(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.categories = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'categories' field has been set */
    public boolean hasCategories() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'categories' field */
    public org.kiji.express.wikimedia.CategoriesRecord.Builder clearCategories() {
      categories = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public CategoriesRecord build() {
      try {
        CategoriesRecord record = new CategoriesRecord();
        record.categories = fieldSetFlags()[0] ? this.categories : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
