/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kiji.express.wikimedia;  
@SuppressWarnings("all")
/** * A custom Avro record to hold complex types for the 'reverted_edits' column of the Wikimedia
    * 'page' table. Specifically, reverted edits are an array of longs. */
@org.apache.avro.specific.AvroGenerated
public class RevertedEditsRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RevertedEditsRecord\",\"namespace\":\"org.kiji.express.wikimedia\",\"doc\":\"* A custom Avro record to hold complex types for the 'reverted_edits' column of the Wikimedia\\n    * 'page' table. Specifically, reverted edits are an array of longs.\",\"fields\":[{\"name\":\"reverted_edits\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.Long> reverted_edits;

  /**
   * Default constructor.
   */
  public RevertedEditsRecord() {}

  /**
   * All-args constructor.
   */
  public RevertedEditsRecord(java.util.List<java.lang.Long> reverted_edits) {
    this.reverted_edits = reverted_edits;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return reverted_edits;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: reverted_edits = (java.util.List<java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'reverted_edits' field.
   */
  public java.util.List<java.lang.Long> getRevertedEdits() {
    return reverted_edits;
  }

  /**
   * Sets the value of the 'reverted_edits' field.
   * @param value the value to set.
   */
  public void setRevertedEdits(java.util.List<java.lang.Long> value) {
    this.reverted_edits = value;
  }

  /** Creates a new RevertedEditsRecord RecordBuilder */
  public static org.kiji.express.wikimedia.RevertedEditsRecord.Builder newBuilder() {
    return new org.kiji.express.wikimedia.RevertedEditsRecord.Builder();
  }
  
  /** Creates a new RevertedEditsRecord RecordBuilder by copying an existing Builder */
  public static org.kiji.express.wikimedia.RevertedEditsRecord.Builder newBuilder(org.kiji.express.wikimedia.RevertedEditsRecord.Builder other) {
    return new org.kiji.express.wikimedia.RevertedEditsRecord.Builder(other);
  }
  
  /** Creates a new RevertedEditsRecord RecordBuilder by copying an existing RevertedEditsRecord instance */
  public static org.kiji.express.wikimedia.RevertedEditsRecord.Builder newBuilder(org.kiji.express.wikimedia.RevertedEditsRecord other) {
    return new org.kiji.express.wikimedia.RevertedEditsRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for RevertedEditsRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RevertedEditsRecord>
    implements org.apache.avro.data.RecordBuilder<RevertedEditsRecord> {

    private java.util.List<java.lang.Long> reverted_edits;

    /** Creates a new Builder */
    private Builder() {
      super(org.kiji.express.wikimedia.RevertedEditsRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.kiji.express.wikimedia.RevertedEditsRecord.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing RevertedEditsRecord instance */
    private Builder(org.kiji.express.wikimedia.RevertedEditsRecord other) {
            super(org.kiji.express.wikimedia.RevertedEditsRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.reverted_edits)) {
        this.reverted_edits = data().deepCopy(fields()[0].schema(), other.reverted_edits);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'reverted_edits' field */
    public java.util.List<java.lang.Long> getRevertedEdits() {
      return reverted_edits;
    }
    
    /** Sets the value of the 'reverted_edits' field */
    public org.kiji.express.wikimedia.RevertedEditsRecord.Builder setRevertedEdits(java.util.List<java.lang.Long> value) {
      validate(fields()[0], value);
      this.reverted_edits = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'reverted_edits' field has been set */
    public boolean hasRevertedEdits() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'reverted_edits' field */
    public org.kiji.express.wikimedia.RevertedEditsRecord.Builder clearRevertedEdits() {
      reverted_edits = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public RevertedEditsRecord build() {
      try {
        RevertedEditsRecord record = new RevertedEditsRecord();
        record.reverted_edits = fieldSetFlags()[0] ? this.reverted_edits : (java.util.List<java.lang.Long>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
