/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kiji.express.wikimedia;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface RevertedEdits {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RevertedEdits\",\"namespace\":\"org.kiji.express.wikimedia\",\"types\":[{\"type\":\"record\",\"name\":\"RevertedEditsRecord\",\"doc\":\"* A custom Avro record to hold complex types for the 'reverted_edits' column of the Wikimedia\\n    * 'page' table. Specifically, reverted edits are an array of longs.\",\"fields\":[{\"name\":\"reverted_edits\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends RevertedEdits {
    public static final org.apache.avro.Protocol PROTOCOL = org.kiji.express.wikimedia.RevertedEdits.PROTOCOL;
  }
}