/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kiji.express.wikimedia;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface RevertingEdits {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RevertingEdits\",\"namespace\":\"org.kiji.express.wikimedia\",\"types\":[{\"type\":\"record\",\"name\":\"RevertingEditsRecord\",\"doc\":\"* A custom Avro record to hold complex types for the 'reverting_edits' column of the Wikimedia\\n    * 'page' table. Specifically, reverting edits are an array of longs.\",\"fields\":[{\"name\":\"reverting_edits\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends RevertingEdits {
    public static final org.apache.avro.Protocol PROTOCOL = org.kiji.express.wikimedia.RevertingEdits.PROTOCOL;
  }
}